### ISSUE TITLE
Theme suggestions

### ISSUE THREAD

**Issue by singhayushh** [DSCKGEC/sac-kgec-web#2]
*This issue doesn't not require any coding. It's just a discussion place to take suggestions for the website's theme*

We are looking for suggestions as of how the website should be designed. Feel free to share images, dribbble shots or links to web designs that you want to suggest for the website. 

In case you don't know what this website is about - SAC KGEC stands for Students' Automobile Club, KGEC. This club deals with the automotive industry where students share thoughts and learning of automobiles and events. 

Tech Stack for frontend is HTML, CSS and JS.

**Comment by singhayushh** [comment]
test comment

**Comment by Gauravmitra-hash** [comment]
Can I help to solve this issue? @singhayushh

**Comment by sorba160** [comment]
Hi, as the theme is not selected yet , I want to make a landing page with a new theme for this website . I want to work on this , let it be assigned for me . @singhayushh 
                         Thanking you, 
                                                          sorbajit goswami

**Comment by singhayushh** [comment]
@Gauravmitra-hash Yeah surely, this issue is open for all for suggestions and discussions. Feel free to drop in any suggestions you have.
