### ISSUE TITLE
Header with top navigation needed

### ISSUE THREAD

**Issue by singhayushh** [DSCKGEC/sac-kgec-web#5]
#### About

As discussed in the previous meet and in compliance with the finalized theme and layout, a responsive header is to be created that will contain the main logo, name of the club and a top navigation as well.

For assets, you can download them directly from [this repo](https://github.com/autokgec/sac)

#### Instructions

- Create a file named header.html under the client directory
- This file will be included as a component in other pages, so make sure you use some variables like title and activeLink etc instead of keeping just static data.

For reference, you can view the header.html file for [KSoC Website](https://github.com/DSCKGEC/kgec-summer-of-code/blob/main/views/header.html)

**Comment by anilphiyak617** [comment]
please assign this issue to me

**Comment by singhayushh** [comment]
You are Anil Phayak, right?
@AkaCoder007

**Comment by anilphiyak617** [comment]
yess
