### ISSUE TITLE
Footer for the website needed

### ISSUE THREAD

**Issue by singhayushh** [DSCKGEC/sac-kgec-web#6]
#### About

As discussed in the previous meet and in compliance with the finalized theme and layout, a responsive footer is to be created that will contain a colophon section on the left and links on the right.

For assets, you can download them directly from [this repo](https://github.com/autokgec/sac), if needed.

#### Instructions

- Create a file named footer.html under the client directory
- This file will be included as a component in other pages, so all js scripts like jquery are to be included as well

For reference, you can view the header.html file for [KSoC Website](https://github.com/DSCKGEC/kgec-summer-of-code/blob/main/views/footer.html)

**Comment by aditya-vinodh** [comment]
Can I implement this?

**Comment by singhayushh** [comment]
Hello @adityavinodh 
Thanks for showing your interests in contributing to this project.

We had a small project meeting yesterday with some other willing contributors and the issues created in the repo, including this, are already assigned to them. You can join our [discord](https://dsck.ml/discord) - this is where we primarily communicate regarding projects and issues.

Feel free to open new issues for other updates. We'll be happy to have you as a contributor.

**Comment by aditya-vinodh** [comment]
Okay, thanks for the info. I didn't see anyone assigned to the issue, so I thought I could contribute.

**Comment by singhayushh** [comment]
> Okay, thanks for the info. I didn't see anyone assigned to the issue, so I thought I could contribute.

Yeah, sorry for that
We'll have the issues assigned soon.

**Comment by sudip-101** [comment]
I want to work on the footer of SAC-KGEC. I was given the task in the discussion meet. 
Please assign it to me @singhayushh Da.

**Comment by singhayushh** [comment]
Thank you for contributing to KSoC. Your PR has been merged
