### ISSUE TITLE
Landing Page for the website

### ISSUE THREAD

**Issue by singhayushh** [DSCKGEC/sac-kgec-web#7]
#### About

As discussed in the previous meet and in compliance with the finalized theme and layout, a responsive landing page is to be created that will contain a carousel of text and images as shown in the meet.

For assets, you can download them directly from [this repo](https://github.com/autokgec/sac), if needed. For other images, make sure you use images with proper license - preferably, from Unsplash.

#### Instructions

- Create a file named index.html under the client directory, if not present
- You do not need to write the starting code for header or footer, import them from header.html and footer.html respectively and start straightaway from the landing section.

For reference, you can view the index.html file for [KSoC Website](https://github.com/DSCKGEC/kgec-summer-of-code/blob/main/views/index.html)

**Comment by sorba160** [comment]
HI, I want to work on this issue . I got the inspiration of landing screen from   https://dribbble.com/shots/10968333-Classic-Cars  here. Kindly assign the issue for me . @singhayushh 
  thank you,
sorbajit goswami .
