### ISSUE TITLE
About page for the website

### ISSUE THREAD

**Issue by singhayushh** [DSCKGEC/sac-kgec-web#8]
#### About

As discussed in the previous meet and in compliance with the finalized theme and layout, a responsive about page is to be created that will contain info about the club along with relevant images and the facebook feed of the club as well.

For assets and data, you can download them directly from [this repo](https://github.com/autokgec/sac)

#### Instructions

- Create a file named about.html under the client directory
- You do not need to write the starting code for header or footer, import them from header.html and footer.html respectively and start straightaway from the about section.

For reference, you can view the index.html file for [KSoC Website](https://github.com/DSCKGEC/kgec-summer-of-code/blob/main/views/header.html) for how to import other html files.

**Comment by Mangalam0512** [comment]
Please assign this issue to me.
