### ISSUE TITLE
Faculty / Team page for the website

### ISSUE THREAD

**Issue by singhayushh** [DSCKGEC/sac-kgec-web#9]
#### About

As discussed in the previous meet and in compliance with the finalized theme and layout, a responsive team page is to be created that will contain info about the team members in card views.

For assets and data, you can download them directly from [this repo](https://github.com/autokgec/sac)

#### Instructions

- Create a file named team.html under the client directory
- You do not need to write the starting code for header or footer, import them from header.html and footer.html respectively and start straightaway from the team section.

For reference, you can view the index.html file for [KSoC Website](https://github.com/DSCKGEC/kgec-summer-of-code/blob/main/views/header.html) for how to import other html files.

**Comment by Arnab-batsy** [comment]
Hi, this is Arnab Kr. Das. I intend to work on this Team page...
